name: Dependabot

permissions:
  contents: write

on:
  pull_request:
    branches:
      - main

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Fetch metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          alert-lookup: true
          github-token: "${{ secrets.GITHUB_TOKEN }}"
